### ISSUE TITLE
clean error

### ISSUE THREAD

**Issue by aresis** [BLPXSPG/CONE#1]
I met some problems when I was trying to run clean_hotel.py 
How can I solve this problem

```
(CONE) D:\code\CONE\data\hotel>python clean_hotel.py
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\11939\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
start to preprocess data
Traceback (most recent call last):
  File "clean_hotel.py", line 222, in <module>
    preprocess(data_dir, save_dir)
  File "clean_hotel.py", line 65, in preprocess
    data = f.readlines()
OSError: [Errno 22] Invalid argument
```

**Comment by BLPXSPG** [comment]
This seems to be an error in loading the data file. Did you download HotelRec?

**Comment by aresis** [comment]
Yes, I downloaded the dataset file according to the link you provided

**Comment by BLPXSPG** [comment]
Where did you save this file?

**Comment by aresis** [comment]
The HotelRec.txt file is located in the \data\hotel\HotelRec folder

**Comment by aresis** [comment]
Can it be due to readlines() causing memory overflow? My memory is only 15.7GB, while HotelRec has over 40 GB

**Comment by BLPXSPG** [comment]
Indeed, it could be. You might want to try running the code with a smaller dataset. I'm not entirely sure though, as I didn't encounter such an error when I ran the code.

**Comment by aresis** [comment]
After extracting 20000 pieces of data from the original document and running the clean file, the problem was resolved

**Comment by aresis** [comment]
I also want to ask a question, there is no aug_translate.py in the hotel folder, only aug_generate.py and aug_translation.py, is it running them separately?

**Comment by BLPXSPG** [comment]
They are two distinct methods of data augmentation, and we used aug_translation.py, which demonstrated better performance.
